org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=ultimate_enchantment
mod_name=Ultimate Enchantment
mod_license=MIT License
mod_version=26.1.2-1.0.0
mod_group_id=com.chen1335.ultimate_enchantment
mod_authors=chen_1335
mod_description="an Enchantment mod"

apotheosis_version=26.1.2-9.0.3
apothic_attributes_version=26.1.2-3.0.1
apothic_enchanting_version=26.1.2-2.0.0
apothic_spawners_version=26.1.2-2.0.1
placebo_version=26.1.2-10.0.2

nashorn_version=15.7
