modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="ultimate_enchantment_apothic_enchanting.mixins.json"

[[mixins]]
config="ultimate_enchantment_enchdesc.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Here's another dependency
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies.${ mod_id }]]
modId = "apothic_enchanting"
type = "optional"
versionRange = "[1.2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "enchdesc"
type = "optional"
versionRange = "[21.1.7,)"
ordering = "NONE"
side = "BOTH"
